Vagrant.configure("2") do |config|
  config.vm.box          = "ubuntu/jammy64"
  config.vm.box_version  = "20241002.0.0"
  config.vm.boot_timeout = 1200

  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = 4096
    vb.cpus   = 4

    # Enable nested virtualization and use KVM paravirt provider
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
  end

  config.vm.cloud_init :user_data,
    content_type: "text/cloud-config",
    path: "config.cfg"

  config.vm.network "forwarded_port", guest: 9000, host: 9000, auto_correct: true
end
