Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.box_version = "20241002.0.0"
  
  config.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "config.cfg"
  end
  